# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  lanchesmac:
    image: lanchesmac
    environment:
     - LANG=pt_BR.UTF-8
     - LC_ALL=pt_BR.UTF-8
     - DB_SERVER= sql
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    depends_on:
      sql:
        condition: service_healthy

  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports: 
      - 1433:1433
    restart: always
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=Peixoto@2019
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-U",
          "SA",
          "-P",
          "Peixoto@2019",
          "-Q",
          "SELECT 1"
        ]
      interval: 10s
      timeout: 30s
      retries: 5
    volumes:
      - ./volume/data:/var/opt/mssql/data
      - ./volume/log:/var/opt/mssql/log
      - ./volume/secrets:/var/opt/mssql/secrets
